name: Generate GitHub Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Generate Contribution Grid
      uses: Platane/snk@v2
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/github-contribution-grid.svg
          dist/github-contribution-grid-dark.svg?palette=github-dark
    
    - name: Push to repository
      uses: EndBug/add-and-commit@v9
      with:
        add: 'dist'
        message: 'Update contribution grid'
        push: origin main --force